REFLECTION_STAGE_TIMEOUT_SECONDS = 12.0
REVIEW_STAGE_TIMEOUT_SECONDS = 30.0
PIPELINE_TIMEOUT_MARGIN_SECONDS = 3.0
PIPELINE_TIMEOUT_SECONDS = (
    REFLECTION_STAGE_TIMEOUT_SECONDS
    + REVIEW_STAGE_TIMEOUT_SECONDS
    + PIPELINE_TIMEOUT_MARGIN_SECONDS
)
