REFLECTION_STAGE_TIMEOUT_SECONDS = 12.0
REVIEW_STAGE_TIMEOUT_SECONDS = 15.0
VERIFIER_STAGE_TIMEOUT_SECONDS = 15.0
MEMORY_STAGE_TIMEOUT_SECONDS = 2.0
PIPELINE_TIMEOUT_MARGIN_SECONDS = 1.0
PIPELINE_TIMEOUT_SECONDS = (
    REFLECTION_STAGE_TIMEOUT_SECONDS
    + REVIEW_STAGE_TIMEOUT_SECONDS
    + VERIFIER_STAGE_TIMEOUT_SECONDS
    + MEMORY_STAGE_TIMEOUT_SECONDS
    + PIPELINE_TIMEOUT_MARGIN_SECONDS
)
